### ISSUE TITLE
Can't save settings file (empty)

### ISSUE THREAD

**Issue by skoch** [SubZane/Sublime-Snipt-Snippet-Fetcher#3]
Installed via Package Manager, went to the settings only to find an empty file. Attempted to fill it out as per a normal settings file and then was prompted that I couldn't save the file.

{ 
    "snipt_username": "skoch", 
    "snipt_apikey": "api-key", 
    "snipt_other_users": "" 
}

**Comment by SubZane** [comment]
maybe the file has become protected. Have you checked the file properties?

**Comment by skoch** [comment]
When I attempt to open the settings file via ST2, a new file is opened in my current window. If I copy the file path to that video I have:

/Users/USERNAME/Library/Application Support/Sublime Text 2/Packages/Snipt.net Snippet Fetcher/Snipt.sublime-settings

If I browse to the actual settings file on the file system I have:
/Users/skoch/Library/Application Support/Sublime Text 2/Packages/Snipt Snippet Fetcher/Snipt.sublime-settings

So it would appear that the file ST2 is attempting to retrieve doesn't have a home to save to!

**Comment by SubZane** [comment]
That's weird, since I'm using Sublimes methods to retrieve that path using `sublime.load_settings()`

I'm not actually setting a path or doing anything than loading the settings file...

**Comment by sashn** [comment]
i propose the following changes:
1) in the plugin, change line 
BASEPATH = sublime.packages_path()+'/Snipt.net Snippet Fetcher/'
to
BASEPATH = sublime.packages_path()+os.sep+'Snipt'+os.sep

2) change documentation regarding the path. the folder for the plugin should be just "Snipt" instead of "Snipt.net Snippet Fetcher".

reasons for this:
- i had the same problems as skoch, sublime kept giving me errors like "No snipt.net username. You must first set you username in: Sublime Text2 ~> Preferences ~> Package Settings ~> Snipt.net Snippet Fetcher ~> Settings" or "Connection refused. Try again later. ....."
- this error originated in the fact that the settings could not be fetched.
- i researched and debugged for some time and it seems that sublime.load_settings expects the given settings-file to have the same name as the folder it resides in. so "XYZ.sublime-settings" needs to be in folder "XYZ". hence my proposed code and documentation changes
- the "os.sep" part just seems more flexible, not sure if it actually makes a difference

PS: also you could change line
sublime.error_message("Connection refused. Try again later. Snipt step: 1"+err)
to
sublime.error_message("Connection refused. Try again later. Snipt step: 1"+str(err))
because otherwise it will try to concatenate a string with an http error object.
